name: lint Markdown file
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install mdl
      run: npm install --global csval
    - name: Run mdl
      uses: actionshub/markdownlint@main
